dev: docker-run: Fix SC2181 - Check exit code directly

diff --git a/bin/docker-run b/bin/docker-run
--- a/bin/docker-run
+++ b/bin/docker-run
@@ -184,8 +184,9 @@ if env | grep -q SSH_AUTH_SOCK && test -n "${DOCKER_MACHINE_NAME}"; then
   trap "bash -c 'ssh -i $HOME/.docker/machine/machines/${DOCKER_MACHINE_NAME}/id_rsa -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -S $SSH_SOCK -O exit docker@${DM_HOST} ; ${CLEANUP_RUN_SCRIPTS} sleep 1; kill $ssh_forwarding_pid ; ssh -i $HOME/.docker/machine/machines/${DOCKER_MACHINE_NAME}/id_rsa -p ${SSH_PORT} -o UserKnownHostsFile=/dev/null -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10  docker@${DM_HOST} rm -f ${DM_AGENT_SOCK} ' &>/dev/null" EXIT HUP INT QUIT TERM
 
   # Check if DM_AGENT_SOCK exists in docker-machine VM
-  ssh -S "$SSH_SOCK" docker@"${DM_HOST}" "[ -e \"$DM_AGENT_SOCK\" ]"
-  [ $? -eq 0 ] || echo "ERROR: DM_AGENT_SOCK path: $DM_AGENT_SOCK does not exist... could not forward SSH_AUTH_SOCK into docker-machine!  Is your ssh-agent running?"
+  if ! ssh -S "$SSH_SOCK" docker@"${DM_HOST}" "[ -e \"$DM_AGENT_SOCK\" ]" ; then
+    echo "ERROR: DM_AGENT_SOCK path: $DM_AGENT_SOCK does not exist... could not forward SSH_AUTH_SOCK into docker-machine!  Is your ssh-agent running?"
+  fi
 fi
 
 
